[package]
name = "maai-core"
version = "0.0.2"
edition = "2021"
description = "maai-core is the core system of the MAAI infrastructure"
license = "MIT"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
